# Generated by Django 4.2.6 on 2023-10-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswa',
            name='id',
        ),
        migrations.AlterField(
            model_name='mahasiswa',
            name='nim',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
